apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ze3ghxnp7-dotnet-basic 
  janus-idp.io/tekton: ze3ghxnp7-dotnet-basic
  backstage.io/kubernetes-id: ze3ghxnp7-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ze3ghxnp7-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml