apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ze3ghxnp7-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ze3ghxnp7-dotnet-basic-gitops